# Netlify configuration file

[build]
  command = "npm run install-deps && npm run build"
  publish = "client/.next"
  functions = "netlify/functions"

[[redirects]]
  # This rule forwards all API requests to our serverless function
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200